### ISSUE TITLE
Advanced Marker Update Modal

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/google-maps-builder#57]
Currently, when you want to edit a marker a lot of the advanced options are out of view and hidden within the marker's repeater group. It would be optimal to bring these options more easily into the user's view by easily clicking from within the marker info window itself and opening them in a modal.

This would allow the user to bulk edit a marker's options without fumbling through to find it in the repeater field. I image a cog icon to click that will open the options in a modal:

![cog](https://cloud.githubusercontent.com/assets/1571635/9216128/24ed60b6-4069-11e5-8771-5b19df53057b.png)
![modal](https://cloud.githubusercontent.com/assets/1571635/9216129/25e163aa-4069-11e5-8c80-b6676a7ad080.png)

**Comment by kevinwhoffman** [comment]
I reviewed this issue with @nishitlangaliya and decided to close. We have already added a `Customize Icon` button in the lower right corner which gives access to editing the marker. And the title/description are editable from the info box itself. The remaining options would be rarely accessed and I don't think warrant a separate modal.
